### ISSUE TITLE
Bump rocket for FESVR with tsi::tick

### ISSUE THREAD

**Issue by seldridge** [ucb-bar/project-template#1]
The current version needs a rocket-chip bump as testchip's csrc/SimSerial.cc appears to be ahead of rocket-chip's riscv-tools/riscv-fesvr. See:
```
project-template/testchipip/csrc/SimSerial.cc:29:10: error: ‘class tsi_t’ has no member named ‘tick’
     tsi->tick(out_valid, out_bits, in_ready);
```

**Comment by zhemao** [comment]
Unfortunately rocket-chip master is too far ahead. So we'll have to point to a branch for now. Thanks.

**Comment by zhemao** [comment]
Should be fixed now.
