### ISSUE TITLE
Not a bug, but why use import "freechips.rocketchip.xxx" when rocket chip uses just xxx?

### ISSUE THREAD

**Issue by pkimelman-nxp** [ucb-bar/project-template#14]
This makes it hard to diff your version of common files from rocket, coreplex, config, etc. I am unclear why this extra name specificity when I would assume you could just default this? 
Also, why do you use "chip" vs. "rocketchip", and the better named "amba" vs. "uncore". I can understand that last one, but is it worth having a different name for the same files?

**Comment by colinschmidt** [comment]
rocket-chip recently refactored its package hierarchy so it also now uses these new names "freechips.rocketchip" and "amba"

**Comment by pkimelman-nxp** [comment]
Ah, OK. Thanks. I guess I have a split in time between them.

Regards, Paul

On Jul 17, 2017, at 4:27 PM, Colin Schmidt <notifications@github.com<mailto:notifications@github.com>> wrote:


rocket-chip recently refactored its package hierarchy so it also now uses these new names "freechips.rocketchip" and "amba"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fucb-bar%2Fproject-template%2Fissues%2F14%23issuecomment-315914038&data=01%7C01%7Cpaul.kimelman%40nxp.com%7C43c6327bef9344efe41b08d4cd6b7127%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0&sdata=tQrGs9lZGNPPn2nGp5vBmF8gcT%2F2RtcqDRfxM2c4ITM%3D&reserved=0>, or mute the thread<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVpF31ieB3NQ_tG6GMmSoX8ZacguXAfjks5sO-31gaJpZM4Oap0t&data=01%7C01%7Cpaul.kimelman%40nxp.com%7C43c6327bef9344efe41b08d4cd6b7127%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0&sdata=0kyneNrDQQAZ71Ea%2BTsNbMECPs9Zj99hdyA7K5tnTrc%3D&reserved=0>.

--
Paul Kimelman – Automotive Platform Architecture
408.906.9676
