### ISSUE TITLE
compiling baremetal

### ISSUE THREAD

**Issue by ninode** [ucb-bar/project-template#18]
Hello, 

I'm compiling the pwm.c program using riscv64-unknown-elf-gcc -o pwm pwm.c and then pk pwm. But it's not working. Should I use LLVM instead ? With clang -target riscv64 -mriscv=RV64IAMFD -S pwm.c -o pwm.S and riscv64-unknown-elf-gcc -o pwm.riscv pwm.S ? 

Is it possible to use pk at all ?

make pwm gives the following: 
```
cc -mcmodel=medany -std=gnu99 -O2 -fno-common -fno-builtin-printf -Wall  -static -nostdlib -nostartfiles -lgcc  pwm.c   -o pwm
cc: error: unrecognized argument in option ‘-mcmodel=medany’
cc: note: valid arguments to ‘-mcmodel=’ are: 32 kernel large medium small
make: *** [pwm] Error 1

```
Thank you

**Comment by colinschmidt** [comment]
That output doesn't look like you are using riscv-gcc. Are you sure its on your PATH?

**Comment by ninode** [comment]
Again, thank you Colin. It solved it

**Comment by ninode** [comment]
Can I run pwm.c without make ? 

I did the following and got the pwm.riscv binary but I didn't use the linker. Is it wrong ?


```
riscv64-unknown-elf-gcc -mcmodel=medany -std=gnu99 -O2 -fno-common -fno-builtin-printf -Wall -c pwm.c -o pwm.o

riscv64-unknown-elf-objdump -D pwm.o > pwm.riscv
```
