### ISSUE TITLE
How to add a custom peripherical signal in the class TestHarness? [FIXED]

### ISSUE THREAD

**Issue by gvillanovanm** [ucb-bar/project-template#31]
I made the pwm example, but now I want to get the peripherical signal in the TestHarness, how to do it?
``` 
class TestHarness(implicit val p: Parameters) extends Module {
  val io = IO(new Bundle {
    val success = Output(Bool())
    val output_perip = Output(Bool())
  })
  val dut = p(BuildTop)(clock, reset.toBool, p)
  dut.debug := DontCare
  dut.connectSimAXIMem()
  dut.dontTouchPorts()
  dut.tieOffInterrupts()
  io.success := dut.connectSimSerial()

  io.output_perip := io_pwmout // ?? Here 
}
```
I wanted my io.output_perip in this module: 
![pwm](https://user-images.githubusercontent.com/32181781/38884694-a29cd508-4270-11e8-8b48-6608a3f384f7.png)

Thanks!

**Comment by zhemao** [comment]
You likely want to do something like this:

    io.output_perip := dut.asInstanceOf[ExampleTopWithPWMModule].io.pwmout

**Comment by gvillanovanm** [comment]
Yes, it works fine now! Thanks.
