### ISSUE TITLE
Usage of $(CHISEL_ARGS) in Makefile

### ISSUE THREAD

**Issue by jimmysitu** [ucb-bar/project-template#38]
https://github.com/ucb-bar/project-template/blob/d48587b6714bbc128566a5d0fac68496d732aa7c/Makefrag#L33

The generator only takes 5 args, and $(CHISEL_ARGS) seems a redundant args?
Any idea?

**Comment by abejgonzalez** [comment]
@zhemao Do you know if this is used anymore? It looks like this was initially added by you at the creation of the repo?

**Comment by abejgonzalez** [comment]
Confirmed that `rocket-chip` does not use this. So this will be deprecated.
