### ISSUE TITLE
init submodules script

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/project-template#61]
We should have one of those

**Comment by abejgonzalez** [comment]
This is addressed in the #55 PR for `rebar` but not for `master`, do we still want one?

**Comment by edtechexplorers** [comment]
I have one in all my downstream templates so I don't much care whether it goes into master now or later.

**Comment by colinschmidt** [comment]
I have one in all my downstream templates so I don't much care whether it goes into master now or later.

**Comment by abejgonzalez** [comment]
I think when `rebar` becomes `master` then this will get solved.

**Comment by jerryz123** [comment]
I believe we have this now.
