### ISSUE TITLE
Is there example projects for Rocc or DMA?

### ISSUE THREAD

**Issue by ViccoYang** [ucb-bar/project-template#9]
Thanks for the detailed MMIO device example, it's very very very helpful.
Now I wonder If there are also detailed example projects for Rocc and DMA ?

For example, I tried to follow the guidance and add a DMA port instead of MMIO, but I
don't know how to make ExtBundle work and how to test it.  Thanks for your help!

**Comment by zhemao** [comment]
There is now an example RoCC configuration that you can take a look at. For DMA, you can look at the BlockDevice or SimpleNIC code in testchipip.
